name: Kotlin PR Checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: kotlinc Personal-Finance-Tracker/src/main/kotlin/datasource/*.kt Personal-Finance-Tracker/src/main/kotlin/models/*.kt Personal-Finance-Tracker/src/main/kotlin/test/*.kt -include-runtime -d test.jar

      - name: Run tests Jar
        run:  java -jar test.jar || exit 1